version: '3.8'

services:
  backend-dev:
    build: .
    container_name: backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
